import type { SessionPayload, UserRole } from "@/types/auth";
export const SESSION_COOKIE_NAME = "datamind_session";
export const SESSION_COOKIE_MAX_AGE_SECONDS = 60 * 30;
export const SESSION_IDLE_TIMEOUT_SECONDS = SESSION_COOKIE_MAX_AGE_SECONDS;
const SESSION_TTL_SECONDS = SESSION_COOKIE_MAX_AGE_SECONDS;
const VALID_ROLES: UserRole[] = ["owner", "admin", "member"];
function getSecret(): string { const secret=process.env.SESSION_SECRET; if(!secret||secret.length<16) throw new Error("SESSION_SECRET is not configured (or is too short)."); return secret; }
function base64UrlEncode(bytes:Uint8Array):string { let binary=""; for(const byte of bytes) binary+=String.fromCharCode(byte); return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,""); }
function base64UrlDecode(value:string):Uint8Array { const padded=value.replace(/-/g,"+").replace(/_/g,"/").padEnd(value.length+((4-(value.length%4))%4),"="); const binary=atob(padded); const bytes=new Uint8Array(binary.length); for(let i=0;i<binary.length;i++) bytes[i]=binary.charCodeAt(i); return bytes; }
function toBufferSource(bytes:Uint8Array):BufferSource{return bytes as unknown as BufferSource;}
async function getHmacKey():Promise<CryptoKey>{return crypto.subtle.importKey("raw",new TextEncoder().encode(getSecret()),{name:"HMAC",hash:"SHA-256"},false,["sign","verify"]);}
export async function createSessionToken(username:string,role:UserRole,employeeId:number|null):Promise<string>{const now=Math.floor(Date.now()/1000);const payload:SessionPayload={username,role,employeeId,iat:now,exp:now+SESSION_TTL_SECONDS};const payloadB64=base64UrlEncode(new TextEncoder().encode(JSON.stringify(payload)));const signature=await crypto.subtle.sign("HMAC",await getHmacKey(),toBufferSource(new TextEncoder().encode(payloadB64)));return `${payloadB64}.${base64UrlEncode(new Uint8Array(signature))}`;}
export async function verifySessionToken(token:string|undefined|null):Promise<SessionPayload|null>{if(!token)return null;const parts=token.split(".");if(parts.length!==2)return null;const[payloadB64,signatureB64]=parts;if(!payloadB64||!signatureB64)return null;try{const valid=await crypto.subtle.verify("HMAC",await getHmacKey(),toBufferSource(base64UrlDecode(signatureB64)),toBufferSource(new TextEncoder().encode(payloadB64)));if(!valid)return null;const payload=JSON.parse(new TextDecoder().decode(base64UrlDecode(payloadB64))) as SessionPayload;if(typeof payload.exp!=="number"||payload.exp<Math.floor(Date.now()/1000))return null;if(!VALID_ROLES.includes(payload.role))return null;if(payload.role!=="owner"&&(typeof payload.employeeId!=="number"||payload.employeeId<=0))return null;return payload;}catch{return null;}}